### PR TITLE
fix NPE if onScrolled fires with no visible children

### PR DESCRIPTION
**Pull request by talklittle**
RecyclerView.onLayout -> dispatchLayout -> dispatchOnScrolled

Fixes GH-8

### CODE REVIEW

**Comment by micHar** [comment]
Didn't 0.1.3 fix this? In example app I tried setting the number of items to 0 and when the recyclerview is empty it just doesn't get scrolled and onScrolled() is not invoked. I didn't want to explicitly make a null check. Can you show me how you initialize your RecyclerView and Adapter so that it crashes in onScrolled()?

If it's still an issue in 0.1.3 I will merge this pull request. Just please don't use another if clause. It should be sufficient to check getChildCount()>0 in the one which is already there. It will be cleaner.

**Comment by talklittle** [comment]
I was able to reproduce the crash on 0.1.3. Here is a sample: https://gist.github.com/talklittle/9c05375c10fafe1c2388

One key thing is `ItemAnimator` must be null. I couldn't reproduce the crash when `ItemAnimator` was set to the `DefaultItemAnimator`.

I managed to trigger `onScrolled` by adding more than 1 item to RecyclerView, `notifyItemRangeInserted(0, 40)` and then removing them, `notifyItemRangeRemoved(0, 40)`. It triggers `onScrolled` in both situations.

With ItemAnimator, the removal of children is deferred, so `onScrolled` still sees the old child count at the time `onLayout` was called. But without ItemAnimator, the children are immediately removed, yet the `onScrolled` is still called, triggering the NPE in FastScroller.

**Comment by talklittle** [comment]
Updated PR to use `recyclerView.getChildCount() > 0`, as requested.

**Comment by micHar** [comment]
@talklittle Thank you very much for checking this! I will release this as 0.1.4 as soon as possible.

**Pull request merged**
